### ISSUE TITLE
Faill to open source file leafcutter.yml

### ISSUE THREAD

**Issue by onionpork** [dieterich-lab/Baltica#21]
Hey there, 

I appreciate your efforts on developing such cool integration method! I am very interested in exploring this method. 
However, I am not familiar with singularity and snakemake. I followed your installation guide. 
And, passed  ```baltica --help```. 
However, when I run ```baltica all data/config.yml --use-singularity```, it showed ```Failed to open source file /home/ychen12/tools/miniconda3/envs/snakemake/lib/python3.9/site-packages/baltica/../envs/leafcutter.yml```
Any idea what should I do? Thank you so much for the help!

BTW, I have changed the paths in config.yml based on your tutorial. 
Again, many thanks for any suggestion!

**Comment by tbrittoborges** [comment]
Hi Yirui,
Thanks for trying our tool!

Commit 94e4bc9292477e675a6f5eab14a31bc3daedca0e should fix your issue. The explanation is that  a new version of Snakemake is activating --use-conda by default, and we don't need that anymore because we have the singularity containers. My commit removes the conda directives.

You need to update the repo and install Baltica again:

``` bash
git pull
pip install . --no-deps
# You can also test it with some test code (it only takes a few minutes)
baltica all data/config.yml --use-singularity
```

Please let me know if you have any other issues. Singularity can be a problem, although I tried to make it as simple as possible within Baltica. Your feedback is much appreciated!

I organized a config for you, assuming you cloned Baltica at `/home/ychen12/baltica`:

```yaml
assembly: GRCh38_90_SIRV
config_path: /home/ychen12/baltica/data/config.yml
contrasts:
  mix2-vs-mix1:
  - mix2
  - mix1
  mix3-vs-mix1:
  - mix3
  - mix1
  mix3-vs-mix2:
  - mix3
  - mix2
fdr: 0.05
leafcutter_max_intron_length: 500000
leafcutter_min_cluster_reads: 30
leafcutter_min_coverage: 20
leafcutter_min_samples_per_group: 3
leafcutter_min_samples_per_intron: 5
majiq_minreads: 5
majiq_non_changing_threshold: 0.05
majiq_threshold: 0.2
orthogonal_result: /home/ychen12/baltica/data/SIRV_changing_introns.gtf
path: /home/ychen12/sirv_test/
project_authors: The authors
project_title: sirv_test
read_len: 101
ref: /home/ychen12/baltica/data/SIRV.gtf
ref_fa: /home/ychen12/baltica/data/SIRV.fa
sample_path: /home/ychen12/baltica/data/
samples:
  mix1_1: mix1_1.bam
  mix1_2: mix1_2.bam
  mix1_3: mix1_3.bam
  mix1_4: mix1_4.bam
  mix1_5: mix1_5.bam
  mix2_1: mix2_1.bam
  mix2_2: mix2_2.bam
  mix2_3: mix2_3.bam
  mix2_4: mix2_4.bam
  mix2_5: mix2_5.bam
  mix3_1: mix3_1.bam
  mix3_2: mix3_2.bam
  mix3_3: mix3_3.bam
  mix3_4: mix3_4.bam
  mix3_5: mix3_5.bam
strandness: fr-firststrand
```
